/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.translator.deutsch.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.translator.deutsch.dto.WordDataDTO;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-23T21:25:46.344001600+01:00[Europe/Madrid]")

@Validated
@Api(value = "Default", description = "the Default API")
public interface DefaultApi {

    /**
     * GET /deutch/{word} : Traduce la palabra intruducida a español
     * Traduce la palabra intruducida a español
     *
     * @param word Palabra en alemán a traducir (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Traduce la palabra intruducida a español", nickname = "deutchWordGet", notes = "Traduce la palabra intruducida a español", response = WordDataDTO.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = WordDataDTO.class) })
    @RequestMapping(value = "/deutch/{word}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<WordDataDTO> deutchWordGet(@ApiParam(value = "Palabra en alemán a traducir",required=true) @PathVariable("word") String word);

}
